name: Publish Rust Crate

on:
  push:
    tags:
      - "v*" # Triggered when pushing version tags, such as v0.0.2
  workflow_dispatch: # Allow manual triggering

jobs:
  publish-crate:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Verify crate
        working-directory: bindings/rust # Directory already correctly specified
        run: |
          mkdir -p vendor/include/xlnpwmon/
          mkdir -p vendor/src
          cp -r ../../include/xlnpwmon/xlnpwmon.h vendor/include/xlnpwmon/
          cp -r ../../src/xlnpwmon.c vendor/src/
          cp -r ../../LICENSE .
          cp -r ../../README.md .
          cargo package --no-verify --allow-dirty

      - name: Publish crate
        working-directory: bindings/rust # Directory already correctly specified
        run: cargo publish --no-verify --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
